namespace: quizapp
replicaCount: 1
image:
  repository: naveentrodo/quizapp
  pullPolicy: IfNotPresent
  tag: "v2"
service:
  type: NodePort
  targetPort: 8080
  port: 8080
  nodePort: 30078
resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 500m
    memory: 600Mi
livenessProbe:
  httpGet:
    path: /question/allQuestions
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 3
readinessProbe:
  httpGet:
    path: /question/allQuestions
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 3
configMapData:
  SPRING_DATASOURCE_URL: "jdbc:mysql://database-1.c7mq86w8a422.us-east-1.rds.amazonaws.com:3306/quizapp"
  SPRING_DATASOURCE_USERNAME: "admin"
  SPRING_DATASOURCE_PASSWORD: "9112Ntorq"   
serviceAccount:
  create: false
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
#volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
#volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

# nodeSelector: {}

# tolerations: []

# affinity: {}
