apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "java-app.fullname" . }}-configmap
  namespace: {{ .Values.namespace}}
  labels:
    {{- include "java-app.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.configMapData }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
      
