apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "java-app.fullname" . }}-monitor
  namespace: {{ .Values.namespace}}
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  endpoints:
    - port: http
      path: "/actuator/prometheus"
