apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "java-app.fullname" . }}-monitor
  namespace: {{ .Values.namespace}}
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  endpoints:
    - port: {{ .Values.service.port }}
      path: "/actuator/prometheus"
